<?php

/**
 * This is also an option in case you want to know about the line earlier on.
 *
 * function custom_line_chart_alter(array &$element, $chart_id) {
 *   $raw_options['yAxis']['plotLines'][] = [
 *     'value' => 3000000,
 *     'color' => 'green',
 *     'dashStyle' => 'shortdash',
 *     'with' => 2,
 *     'label' => [
 *       'text' => 'foo',
 *     ],
 *   ];
 *   if (isset($element['#raw_options'])) {
 *     $element['#raw_options'] = NestedArray::mergeDeepArray([
 *       $element['#raw_options'],
 *       $raw_options,
 *     ]);
 *   }
 *   $element['#raw_options'] = $raw_options;
 * }
 */

/*
 * Implements hook_chart_definition_alter().
 */
function custom_line_chart_definition_alter(array &$definition, array $element, $chart_id) {
  if ($element['#chart_library'] === 'highcharts') {
    $view = $element['#view'];
    $minValue = $view->header['my_custom_view_area']->options['min']['data_min'];
    $maxValue = $view->header['my_custom_view_area']->options['max']['data_max'];
    $minLabel = $view->header['my_custom_view_area']->options['min']['min_label'];
    $maxLabel = $view->header['my_custom_view_area']->options['max']['max_label'];
    $minColor = $view->header['my_custom_view_area']->options['min']['min_color'];
    $maxColor = $view->header['my_custom_view_area']->options['max']['max_color'];
    $dashStyle = $view->header['my_custom_view_area']->options['dash_style'];

    $definition['yAxis']['plotLines'][] = [
      'value' => $minValue,
      'color' => $minColor,
      'dashStyle' => $dashStyle,
      'width' => 2,
      'label' => [
        'text' => $minLabel,
      ],
    ];

    $definition['yAxis']['plotLines'][] = [
      'value' => $maxValue,
      'color' => $maxColor,
      'dashStyle' => $dashStyle,
      'width' => 2,
      'label' => $maxLabel,
    ];
  }
}
