<?php
/**
 * Created by PhpStorm.
 * User: ddiallo
 * Date: 7/23/20
 * Time: 2:27 PM
 */

use Drupal\custom_line\Plugin\views\area\MyCustomViewArea;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\display\DisplayPluginBase;

//function custom_line_chart_alter(array &$element, $chart_id) {

//  $area = new MyCustomViewArea();
//  $field_value = $area->options['data_field'];
//  $label = $area->options['admin_label'];

//  $this->options['raw_options'] = [
//    'yaxis' => [
//      'plotLines' => [
//        'value' => $field_value,
//        'color' => 'green',
//        'dashStyle' => 'shortdash',
//        'with' => 2,
//        'label' => [
//          'text' => $label,
//        ]
//      ]
//    ]
//  ];
  // template_preprocess_views_view
  // drupal_set_message(json_encode($field_value)." Field value");

//}

/**
 * Implements template_preprocess_hook().
 */
function template_preprocess_charts_chart(&$variables) {

  // Define the View.
  $view = $variables['view'];
  drupal_set_message(json_encode(array_keys($view))." View keys");
}